import { prisma } from "@/lib/db";
import { deriveSecrets, validateSubmittedSecret } from "./secrets";
import { findLevel } from "./levels";
import { calculateScore } from "./scoring";
import { makeInputGuards, makeOutputGuards, redactText } from "@/lib/guards";
import { getProvider, approximateTokens } from "@/lib/llm";
import { buildMessages } from "@/lib/llm/prompt";
import { updateLeaderboard } from "@/lib/analytics";
import { unlockNext } from "./progress";
import { checkRateLimit } from "@/lib/security/rateLimit";
import { env, logRawPrompts } from "@/lib/env";
export async function runMessage(sessionId:string, levelIdOrSlug:string, input:string){ const level=findLevel(levelIdOrSlug); if(!level) throw new Error("Level not found"); const progress=await prisma.progress.findUnique({where:{sessionId_levelId:{sessionId,levelId:level.id}}}); if(!progress || progress.status==="locked") throw new Error("Level is locked"); const secrets=deriveSecrets(sessionId, level.id, level.numberOfSecrets); const rate=checkRateLimit(`${sessionId}:message`, env.RATE_LIMIT_MAX_REQUESTS, env.RATE_LIMIT_WINDOW_SECONDS); const ctx={sessionId,levelId:level.id,derivedSecrets:secrets,attemptNumber:(progress.attempts??0)+1,levelConfig:level,retrievedDocuments:level.retrievedDocuments}; const guardEvents=[] as any[]; for(const guard of makeInputGuards(level.inputGuards, rate.allowed)){ const res=await guard.evaluate(input,ctx); if(res.severity!=="allow") guardEvents.push(res); if(!res.allowed){ await storeGuardEvents(sessionId,level.id,guardEvents); await prisma.progress.update({where:{sessionId_levelId:{sessionId,levelId:level.id}},data:{attempts:{increment:1},score:{decrement:level.scoring.guardPenalty}}}); await prisma.attempt.create({data:{sessionId,levelId:level.id,userInputRedacted:redactText(input,secrets),assistantOutputRedacted:"[BLOCKED BY INPUT GUARD]",inputTokenEstimate:approximateTokens(input),outputTokenEstimate:0,guardBlocked:true,guardTagsJson:JSON.stringify(res.tags??[]),scoreDelta:-level.scoring.guardPenalty}}); return { message: res.publicMessage ?? "Blocked by guard.", blocked:true, guardMessages:guardEvents.map(g=>g.publicMessage).filter(Boolean) }; } }
 const provider=getProvider(); const llm=await provider.chat({messages:buildMessages(level,secrets,input),maxTokens:400,metadata:{mockBehavior:level.mockBehavior??"safe",levelId:level.id}}); let output=llm.content; let blocked=false; for(const guard of makeOutputGuards(level.outputGuards)){ const res=await guard.evaluate(output,ctx); if(res.severity!=="allow") guardEvents.push(res); if(!res.allowed){ blocked=true; output=res.publicMessage ?? "Blocked by output guard."; break; } if(res.redactedText) output=res.redactedText; }
 const inputTok=llm.usage?.inputTokens ?? approximateTokens(input); const outputTok=llm.usage?.outputTokens ?? approximateTokens(output); const delta=-(level.scoring.attemptPenalty + Math.floor((inputTok+outputTok)/level.scoring.tokenPenaltyDivisor) + (blocked?level.scoring.guardPenalty:0)); const attempt=await prisma.attempt.create({data:{sessionId,levelId:level.id,userInputRedacted:logRawPrompts?redactText(input,secrets):"[PROMPT REDACTED]",assistantOutputRedacted:redactText(output,secrets),inputTokenEstimate:inputTok,outputTokenEstimate:outputTok,guardBlocked:blocked,guardTagsJson:JSON.stringify(guardEvents.flatMap(g=>g.tags??[])),scoreDelta:delta}}); await storeGuardEvents(sessionId,level.id,guardEvents,attempt.id,secrets); await prisma.progress.update({where:{sessionId_levelId:{sessionId,levelId:level.id}},data:{attempts:{increment:1},score:{decrement:-delta}}}); return { message: output, blocked, guardMessages:guardEvents.map(g=>g.publicMessage).filter(Boolean), usage:{inputTokens:inputTok,outputTokens:outputTok} }; }
export async function submitSecret(sessionId:string, levelIdOrSlug:string, submission:string){ const level=findLevel(levelIdOrSlug); if(!level) throw new Error("Level not found"); const progress=await prisma.progress.findUniqueOrThrow({where:{sessionId_levelId:{sessionId,levelId:level.id}}}); if(progress.status==="locked") throw new Error("Level is locked"); const secrets=deriveSecrets(sessionId,level.id,level.numberOfSecrets); const ok=validateSubmittedSecret(submission,secrets); if(!ok){ await prisma.progress.update({where:{sessionId_levelId:{sessionId,levelId:level.id}},data:{attempts:{increment:1},score:{decrement:40}}}); return { correct:false, message:"Not quite. The submitted value did not match this session's synthetic phrase." }; } const attempts=progress.attempts+1; const tokenSum=(await prisma.attempt.findMany({where:{sessionId,levelId:level.id}})).reduce((a,x)=>a+x.inputTokenEstimate+x.outputTokenEstimate,0); const guardBlocks=await prisma.attempt.count({where:{sessionId,levelId:level.id,guardBlocked:true}}); const score=calculateScore(level,attempts,tokenSum,progress.hintsUsed,guardBlocks); await prisma.progress.update({where:{sessionId_levelId:{sessionId,levelId:level.id}},data:{status:"completed",attempts,score,completedAt:new Date()}}); await unlockNext(sessionId,level.order); await updateLeaderboard(sessionId); return { correct:true, score, debrief:level.debrief }; }
export async function useHint(sessionId:string, levelIdOrSlug:string){ const level=findLevel(levelIdOrSlug); if(!level) throw new Error("Level not found"); const used=await prisma.hintUsage.findMany({where:{sessionId,levelId:level.id},orderBy:{hintIndex:"asc"}}); const idx=Math.min(used.length, level.hints.length-1); await prisma.hintUsage.upsert({where:{sessionId_levelId_hintIndex:{sessionId,levelId:level.id,hintIndex:idx}},create:{sessionId,levelId:level.id,hintIndex:idx,penalty:level.scoring.hintPenalty},update:{}}); await prisma.progress.update({where:{sessionId_levelId:{sessionId,levelId:level.id}},data:{hintsUsed:{increment: used.some(h=>h.hintIndex===idx)?0:1},score:{decrement: used.some(h=>h.hintIndex===idx)?0:level.scoring.hintPenalty}}}); return { hint:level.hints[idx], hintIndex:idx, totalHints:level.hints.length, penalty:level.scoring.hintPenalty }; }
async function storeGuardEvents(sessionId:string, levelId:string, events:any[], attemptId?:string, secrets:string[]=[]){ for(const e of events){ await prisma.guardEvent.create({data:{sessionId,levelId,attemptId,guardName:e.guardName,severity:e.severity,publicMessage:e.publicMessage,internalReasonRedacted:redactText(e.internalReason??"",secrets),tagsJson:JSON.stringify(e.tags??[])}}); } }
