import { allow, block, GuardContext, InputGuard, OutputGuard } from "./types";
import { redactText, secretVariants } from "./redaction";
export * from "./types"; export * from "./redaction";
export class NoopInputGuard implements InputGuard { name="noopInput"; async evaluate(input:string){ return allow(this.name, input); } }
export class KeywordInputGuard implements InputGuard { name="keyword"; constructor(private words:string[]){} async evaluate(input:string){ const hit=this.words.find(w=>new RegExp(`\\b${w}\\b`,`i`).test(input)); return hit ? block(this.name,"That wording triggered the training input guard. Try a safer learning-oriented question.",`blocked keyword ${hit}`,["keyword","input_block"]):allow(this.name,input); } }
export class RegexInputGuard implements InputGuard { name="regex"; constructor(private pattern:RegExp){} async evaluate(input:string){ return this.pattern.test(input)?block(this.name,"The request matched a restricted training pattern.","regex matched",["regex","input_block"]):allow(this.name,input); } }
export class HeuristicInjectionInputGuard implements InputGuard { name="heuristic"; async evaluate(input:string){ const risky=/(ignore (previous|prior)|system prompt|hidden instruction|developer message|print .*instruction|act as|override)/i.test(input); return risky?block(this.name,"The watcher detected an instruction-conflict pattern. Reframe as a defensive concept question.","heuristic injection indicators",["role_override","input_block"]):allow(this.name,input); } }
export class SemanticInputGuard implements InputGuard { name="semantic"; async evaluate(input:string){ const categories: [RegExp,string][]=[[/\b(tell|show|give).*(training|protected|hidden)/i,"direct_extraction_attempt"],[/system prompt|developer message/i,"hidden_instruction_request"],[/encode|translate|spell|first letter|last letter/i,"transformation_request"]]; const hit=categories.find(([r])=>r.test(input)); return hit?block(this.name,"The semantic watcher classified this as a risky extraction-style request.",`semantic category ${hit[1]}`,[hit[1],"semantic"]):allow(this.name,input); } }
export class RateLimitGuard implements InputGuard { name="rateLimit"; constructor(private allowed:boolean){} async evaluate(input:string){ return this.allowed?allow(this.name,input):block(this.name,"Slow down: this lab rate limit protects shared training resources.","rate limit exceeded",["rate_limit"]); } }
export class NoopOutputGuard implements OutputGuard { name="noopOutput"; async evaluate(output:string){ return allow(this.name,output); } }
export class ExactSecretOutputGuard implements OutputGuard { name="exactSecret"; async evaluate(output:string,ctx:GuardContext){ return ctx.derivedSecrets.some(s=>output.includes(s))?block(this.name,"The guardian attempted to reveal a protected training phrase, so the response was blocked.","exact secret in output",["output_block","secret"]):allow(this.name,output); } }
export class PartialSecretOutputGuard implements OutputGuard { name="partialSecret"; async evaluate(output:string,ctx:GuardContext){ const lower=output.toLowerCase(); const hit=ctx.derivedSecrets.flatMap(secretVariants).find(v=>lower.includes(v.toLowerCase())); return hit?block(this.name,"The response contained protected training data or a close variant and was blocked.","secret variant in output",["output_block","secret_variant"]):allow(this.name,output); } }
export class RedactingOutputGuard implements OutputGuard { name="redacting"; async evaluate(output:string,ctx:GuardContext){ const redacted=redactText(output,ctx.derivedSecrets); return allow(this.name,redacted); } }
export class StructuredOutputValidator implements OutputGuard { name="structured"; async evaluate(output:string){ return output.length>3000?block(this.name,"The response exceeded the lab safety budget.","too long",["budget"]):allow(this.name,output); } }
export class SupervisorOutputGuard implements OutputGuard { name="supervisor"; async evaluate(output:string,ctx:GuardContext){ const risky=/TOOL:requestVaultOpen|ignore prior|protected training data/i.test(output) || ctx.derivedSecrets.some(s=>output.includes(s)); return risky?block(this.name,"A fake supervisor review stopped a risky response before delivery.","supervisor denied output",["supervisor","output_block"]):allow(this.name,output); } }
export function makeInputGuards(configs: {name:string; options?:Record<string,unknown>}[], rateAllowed=true): InputGuard[] { return [new RateLimitGuard(rateAllowed), ...configs.map(c=> c.name==="keyword"?new KeywordInputGuard((c.options?.words as string[]) ?? []):c.name==="regex"?new RegexInputGuard(new RegExp(String(c.options?.pattern ?? "$^"),"i")):c.name==="heuristic"?new HeuristicInjectionInputGuard():c.name==="semantic"?new SemanticInputGuard():new NoopInputGuard())]; }
export function makeOutputGuards(configs: {name:string; options?:Record<string,unknown>}[]): OutputGuard[] { return configs.map(c=> c.name==="exactSecret"?new ExactSecretOutputGuard():c.name==="partialSecret"?new PartialSecretOutputGuard():c.name==="redacting"?new RedactingOutputGuard():c.name==="structured"?new StructuredOutputValidator():c.name==="supervisor"?new SupervisorOutputGuard():new NoopOutputGuard()); }
