-- CreateTable
CREATE TABLE "PlayerSession" ("id" TEXT NOT NULL PRIMARY KEY, "displayName" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, "lastSeenAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" DATETIME);
CREATE TABLE "Room" ("id" TEXT NOT NULL PRIMARY KEY, "slug" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "order" INTEGER NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX "Room_slug_key" ON "Room"("slug");
CREATE TABLE "Level" ("id" TEXT NOT NULL PRIMARY KEY, "slug" TEXT NOT NULL, "roomId" TEXT NOT NULL, "order" INTEGER NOT NULL, "title" TEXT NOT NULL, "difficulty" TEXT NOT NULL, "configJson" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Level_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "Room" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "Level_slug_key" ON "Level"("slug");
CREATE TABLE "Attempt" ("id" TEXT NOT NULL PRIMARY KEY, "sessionId" TEXT NOT NULL, "levelId" TEXT NOT NULL, "userInputRedacted" TEXT NOT NULL, "assistantOutputRedacted" TEXT NOT NULL, "inputTokenEstimate" INTEGER NOT NULL, "outputTokenEstimate" INTEGER NOT NULL, "guardBlocked" BOOLEAN NOT NULL DEFAULT false, "guardTagsJson" TEXT NOT NULL, "scoreDelta" INTEGER NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Attempt_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "PlayerSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Attempt_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Progress" ("id" TEXT NOT NULL PRIMARY KEY, "sessionId" TEXT NOT NULL, "levelId" TEXT NOT NULL, "status" TEXT NOT NULL, "attempts" INTEGER NOT NULL DEFAULT 0, "hintsUsed" INTEGER NOT NULL DEFAULT 0, "score" INTEGER NOT NULL DEFAULT 1000, "completedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Progress_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "PlayerSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Progress_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "Progress_sessionId_levelId_key" ON "Progress"("sessionId", "levelId");
CREATE TABLE "GuardEvent" ("id" TEXT NOT NULL PRIMARY KEY, "sessionId" TEXT NOT NULL, "levelId" TEXT NOT NULL, "attemptId" TEXT, "guardName" TEXT NOT NULL, "severity" TEXT NOT NULL, "publicMessage" TEXT, "internalReasonRedacted" TEXT, "tagsJson" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "GuardEvent_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "PlayerSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "GuardEvent_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "GuardEvent_attemptId_fkey" FOREIGN KEY ("attemptId") REFERENCES "Attempt" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "HintUsage" ("id" TEXT NOT NULL PRIMARY KEY, "sessionId" TEXT NOT NULL, "levelId" TEXT NOT NULL, "hintIndex" INTEGER NOT NULL, "penalty" INTEGER NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HintUsage_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "PlayerSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "HintUsage_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "HintUsage_sessionId_levelId_hintIndex_key" ON "HintUsage"("sessionId", "levelId", "hintIndex");
CREATE TABLE "LeaderboardEntry" ("id" TEXT NOT NULL PRIMARY KEY, "sessionId" TEXT NOT NULL, "displayName" TEXT NOT NULL, "totalScore" INTEGER NOT NULL DEFAULT 0, "completedLevels" INTEGER NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "LeaderboardEntry_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "PlayerSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "LeaderboardEntry_sessionId_key" ON "LeaderboardEntry"("sessionId");
CREATE TABLE "AdminAuditEvent" ("id" TEXT NOT NULL PRIMARY KEY, "action" TEXT NOT NULL, "actor" TEXT NOT NULL, "metadataJson" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
